Class {
	#name : #Bibliotheque,
	#superclass : #Object,
	#category : #'PBDataAnalyse-model'
}

{ #category : #'as yet unclassified' }
Bibliotheque >> numberOfEvolutionPerYear [
]

{ #category : #'as yet unclassified' }
Bibliotheque >> numberOfImportantPerYear [
]

{ #category : #'as yet unclassified' }
Bibliotheque >> numberOfRunAnomaliePerYear [
]

{ #category : #'as yet unclassified' }
Bibliotheque >> numberOfTresImportantPerYear [
]

{ #category : #'as yet unclassified' }
Bibliotheque >> numberOfUrgentPerYear [
]
